language: go
os: linux
dist: xenial
branches:
  only:
    - master
addons:
 snaps:
   - hugo
before_install:
  - openssl aes-256-cbc -K $encrypted_1a8ba66f9725_key -iv $encrypted_1a8ba66f9725_iv -in .travis.key.enc -out .travis.key -d
script: bash ./.travis.sh
